// SPDX-FileCopyrightText: 2026 Cycl0o0 <contact@cyclooo.fr>
// SPDX-License-Identifier: AGPL-3.0-or-later

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/cycl0o0/cartui/internal/config"
	"github.com/cycl0o0/cartui/internal/tui/setup"
	"github.com/spf13/cobra"
)

// newSetupCmd returns `cartui setup` — the first-run welcome flow.
//
// Asks the user how they want to source map data, then writes the
// chosen settings into the user's config.toml so the next `cartui`
// run uses them by default.
func newSetupCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "setup",
		Short: "Pick a map data source through an interactive welcome screen",
		Long: `Run an interactive welcome that walks you through picking a map
data source for CarTUI: free vector tiles (OpenFreeMap), Mapbox with
your own key, Protomaps PMTiles, public or self-hosted Overpass, or
an offline OSM database.

The chosen settings are appended to your config.toml so they apply
to every subsequent run.`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runSetup()
		},
	}
}

// runSetup launches the interactive welcome and applies its result.
func runSetup() error {
	model := setup.New()
	prog := tea.NewProgram(model, tea.WithAltScreen())
	finalModel, err := prog.Run()
	if err != nil {
		return fmt.Errorf("setup tui: %w", err)
	}
	m, ok := finalModel.(setup.Model)
	if !ok {
		return fmt.Errorf("setup: unexpected model type %T", finalModel)
	}
	if !m.Done() {
		return nil
	}

	res := m.Result()
	if res.Choice == setup.ChoiceCancel || res.Choice == setup.ChoiceUnset {
		fmt.Println("Setup annulé — config inchangée.")
		return nil
	}

	cfg, err := config.Load("")
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}
	applySetupResult(&cfg, res)

	dir, err := config.DefaultDir()
	if err != nil {
		return fmt.Errorf("config dir: %w", err)
	}
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("mkdir config: %w", err)
	}
	path := filepath.Join(dir, "config.toml")
	if err := writeConfigTOML(path, cfg); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	fmt.Printf("✓ Configuration enregistrée dans %s\n", path)
	if res.Choice == setup.ChoiceOfflinePBF {
		fmt.Println()
		fmt.Println("Pour activer la source hors-ligne, lance :")
		fmt.Println()
		fmt.Println("    cartui pbf-download aquitaine     # ou: france / europe / planet")
		fmt.Println()
		fmt.Println("Ça télécharge l'extract PBF et écrit `providers.pbf_path` dans ta config.")
		fmt.Println("Le prochain `cartui` chargera la base locale en RAM (pas de réseau ensuite).")
	}
	return nil
}

// applySetupResult mutates cfg according to what the user picked.
//
// We mirror the priority chain in main.go (PMTiles > Mapbox >
// OpenFreeMap > Overpass) so a single welcome answer cleanly selects
// exactly one source. Unselected fields are zeroed so a previous run
// doesn't bleed through.
func applySetupResult(cfg *config.Config, r setup.Result) {
	cfg.Providers.PMTilesURL = ""
	cfg.Providers.MapboxToken = ""
	cfg.Providers.OpenFreeMapURL = ""
	cfg.Providers.OverpassURL = ""
	cfg.Providers.PBFPath = ""

	switch r.Choice {
	case setup.ChoiceOpenFreeMap:
		cfg.Providers.OpenFreeMapURL = "https://tiles.openfreemap.org/planet"
	case setup.ChoiceMapbox:
		cfg.Providers.MapboxToken = r.MapboxToken
		cfg.Providers.MapboxTileset = "mapbox.mapbox-streets-v8"
	case setup.ChoicePMTiles:
		cfg.Providers.PMTilesURL = r.PMTilesURL
	case setup.ChoiceOverpassPublic:
		// Empty -> default rotation.
	case setup.ChoiceOverpassLocal:
		cfg.Providers.OverpassURL = r.OverpassURL
	case setup.ChoiceOfflinePBF:
		// The setup screen records the region name only; the actual
		// PBF download is deferred to `cartui pbf-download <region>`.
		// We seed OpenFreeMap as a sensible fallback in the meantime.
		cfg.Providers.OpenFreeMapURL = "https://tiles.openfreemap.org/planet"
	}
}

// writeConfigTOML serialises a [config.Config] back to a TOML file.
// We hand-write the document instead of pulling a TOML encoder so the
// output stays human-friendly with our own grouping and comments.
func writeConfigTOML(path string, cfg config.Config) error {
	var b strings.Builder
	b.WriteString("# CarTUI user configuration — generated by `cartui setup`.\n")
	b.WriteString("# You can edit this file freely; rerun setup anytime.\n\n")

	b.WriteString("[ui]\n")
	fmt.Fprintf(&b, "theme   = %q\n", cfg.UI.Theme)
	fmt.Fprintf(&b, "sidebar = %t\n", cfg.UI.Sidebar)
	fmt.Fprintf(&b, "lang    = %q\n", cfg.UI.Lang)
	b.WriteString("\n")

	b.WriteString("[map]\n")
	fmt.Fprintf(&b, "default_lat  = %g\n", cfg.Map.DefaultLat)
	fmt.Fprintf(&b, "default_lng  = %g\n", cfg.Map.DefaultLng)
	fmt.Fprintf(&b, "default_zoom = %d\n", cfg.Map.DefaultZoom)
	fmt.Fprintf(&b, "braille      = %t\n", cfg.Map.Braille)
	b.WriteString("\n")

	b.WriteString("[providers]\n")
	writeStringField(&b, "nominatim_url", cfg.Providers.NominatimURL)
	writeStringField(&b, "overpass_url", cfg.Providers.OverpassURL)
	writeStringField(&b, "osrm_url", cfg.Providers.OSRMURL)
	writeStringField(&b, "osrm_profile", cfg.Providers.OSRMProfile)
	writeStringField(&b, "tile_url", cfg.Providers.TileURL)
	writeStringField(&b, "tomtom_url", cfg.Providers.TomTomURL)
	writeStringField(&b, "tomtom_api_key", cfg.Providers.TomTomAPIKey)
	writeStringField(&b, "pmtiles_url", cfg.Providers.PMTilesURL)
	writeStringField(&b, "mapbox_token", cfg.Providers.MapboxToken)
	writeStringField(&b, "mapbox_tileset", cfg.Providers.MapboxTileset)
	writeStringField(&b, "mapbox_url", cfg.Providers.MapboxURL)
	writeStringField(&b, "openfreemap_url", cfg.Providers.OpenFreeMapURL)
	writeStringField(&b, "pbf_path", cfg.Providers.PBFPath)
	b.WriteString("\n")

	b.WriteString("[providers.rate]\n")
	fmt.Fprintf(&b, "nominatim_rps = %g\n", cfg.Providers.Rate.NominatimRPS)
	fmt.Fprintf(&b, "overpass_rps  = %g\n", cfg.Providers.Rate.OverpassRPS)
	fmt.Fprintf(&b, "osrm_rps      = %g\n", cfg.Providers.Rate.OSRMRPS)
	fmt.Fprintf(&b, "tile_rps      = %g\n", cfg.Providers.Rate.TileRPS)
	b.WriteString("\n")

	b.WriteString("[cache]\n")
	fmt.Fprintf(&b, "tile_ttl_hours       = %d\n", cfg.Cache.TileTTLHours)
	fmt.Fprintf(&b, "overpass_ttl_minutes = %d\n", cfg.Cache.OverpassTTLMinutes)
	b.WriteString("\n")

	b.WriteString("[network]\n")
	fmt.Fprintf(&b, "timeout_seconds = %d\n", cfg.Network.TimeoutSeconds)
	fmt.Fprintf(&b, "retries         = %d\n", cfg.Network.Retries)
	b.WriteString("\n")

	return os.WriteFile(path, []byte(b.String()), 0o600)
}

// writeStringField writes `key = "value"` (always quoted) so empty
// strings appear as `key = ""` rather than disappearing.
func writeStringField(b *strings.Builder, key, value string) {
	fmt.Fprintf(b, "%-15s = %q\n", key, value)
}
